#!/bin/bash

# Crowd Linux service controller script
cd "/opt/atlassian/crowd"

case "$1" in
    start)
        ./start_crowd.sh
        ;;
    stop)
        ./stop_crowd.sh
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
